name: Docker Image CI

on:
  push:
    branches: [ "master" ]
    paths-ignore: ["react-app/**", "README.md"]
  pull_request:
    branches: [ "master" ]
    paths-ignore: ["react-app/**", "README.md"]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: build the docker image
      run: docker build . --file Dockerfile --tag yickysan/basoene-app:${{ github.sha }}
    - name: docker push
      run: docker push yickysan/basoene-app:${{ github.sha }}